version: "3.1"

services:

  db:
    container_name: postgres_activities_list
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"

